### ISSUE TITLE
GitHub Actions security hardening for this repository

### ISSUE THREAD

**Issue by HonkingGoose** [dangoslen/dependabot-changelog-helper#104]
## Introduction

I think I found some things for you to look into. I've linked to relevant documentation so you can review the docs and decide what to do. 😉 

### `pull_request_target` in workflow files

You're using `pull_request_target` in your workflow files, for example:

https://github.com/dangoslen/dependabot-changelog-helper/blob/4735b98713bc2d4ae49f00221196489900f47a6c/.github/workflows/pull-request.yml#L3

This may be dangerous. Here's a quote from GitHub's security lab blog post: [^security-lab]

> TL;DR: Combining `pull_request_target` workflow trigger with an explicit checkout of an untrusted PR is a dangerous practice that may lead to repository compromise.

[^security-lab]: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

### Manually approve workflow run from public forks

You may want to require manual approval _before_ a workflow runs from a public fork. Quote: [^gh-docs-workflow-approval]

> Anyone can fork a public repository, and then submit a pull request that proposes changes to the repository's GitHub Actions workflows. Although workflows from forks do not have access to sensitive data such as secrets, they can be an annoyance for maintainers if they are modified for abusive purposes.
>
> To help prevent this, workflows on pull requests to public repositories from some outside contributors will not run automatically, and might need to be approved first. By default, all first-time contributors require approval to run workflows.
>
> **Note**
> Workflows triggered by `pull_request_target` events are run in the context of the base branch. Since the base branch is considered trusted, workflows triggered by these events will always run, regardless of approval settings.

Because you're using `pull_request_target` the workflow ran immediately on my PR, as mentioned in the quote above.

[^gh-docs-workflow-approval]: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

### Security hardening for GitHub Actions

GitHub has good documentation on how to improve the security hardening of your actions. [^gh-docs-security-hardening]

> This guide explains how to configure security hardening for certain GitHub Actions features.

[^gh-docs-security-hardening]: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions

**Comment by dangoslen** [comment]
Hey @HonkingGoose! Thank you for raising this.

I'm aware of these issues and have implemented them in other repos.. just haven't fully gotten around to this one. I should have time this week to address them and get it complete

And thank you for your PR!

**Comment by HonkingGoose** [comment]
You're welcome! 😄 I'll let you fix these things then. 😉
