### ISSUE TITLE
Document Changes for each PR

### ISSUE THREAD

**Issue by vbrandl** [dangoslen/dependabot-changelog-helper#148]
From what I can see, if I bump a dependency from x to y and y to z in separate PRs but the same release cycle, this action would create only one line in the changelog: "Bump ... from x to z".
I like to document and link each merged PR in my changelog.
Currently (and I do this by hand) I have one changelog entry for each PR:

```
* Bump ... from x to y (#1)
* Bump ... from y to z (#2)
```

Another alternative but maybe slightly more complex to implement would be something like this:

```
* Bump ... from x to z (#1, #2)
```

If you are open to it, I might try to implement something like described for this action. If so, which way would you prefer? Multiple entries or a single entry with multiple links?

**Comment by dangoslen** [comment]
I like this idea a lot! 

I especially think the second option you list will be the better path forward here. I worry about creating too much configuration to manage how subsequent package updates get added to the changelog. The second option keeps the existing functionality easily while adding really helpful context - and I think it won't be a ton of work to this.

I'd love to see a PR for this and will be happy to review it! I'll try an implementation myself to see where gotchas might be too.

**Comment by dangoslen** [comment]
@vbrandl I did a [quick prototype](https://github.com/dangoslen/dependabot-changelog-helper/pull/149) of what I think a starting point for this might look like! Feel free to take a look at that.  I'd like to get you the contribution if you are up for it!

**Comment by vbrandl** [comment]
I tried adding this action to one of my projects by using the action template from your readme (btw the readme still suggests using `@v2`): https://github.com/vbrandl/petnames-generator/blob/master/.github/workflows/changelog.yml

The action was executed but didn't create a change in my CHANGELOG.md: hhttps://github.com/vbrandl/petnames-generator/actions/runs/4897017330/jobs/8744541692

**Comment by dangoslen** [comment]
Hi @vbrandl 

Thanks for bringing this up. From what I can tell, you need to add some action to commit the change to your branch. I use [this auto-commit action](https://github.com/stefanzweifel/git-auto-commit-action). An example of it's use is in the [workflows for this repo](https://github.com/dangoslen/dependabot-changelog-helper/blob/main/.github/workflows/pull-request.yml#L60)

BUT I see what you are saying - I need to add that context in the example in the README. I'll do that shortly.

**Comment by vbrandl** [comment]
Should have read the whole example... Ty
