### ISSUE TITLE
Support nested lists in changelogs

### ISSUE THREAD

**Issue by tisoft** [dangoslen/dependabot-changelog-helper#161]
I have nested lists in my changelog, which get corrupted with this action:

Given the changelog
```md
## [Unreleased]
### Fixed
- MQTT
  - calculate correct tyre pressure
```
I expect the following updated changelog
```md
## [Unreleased]
### Fixed
- MQTT
  - calculate correct tyre pressure
### Dependencies
- Bump `maven-source-plugin` from 3.2.1 to 3.3.0 (#23)
```
but  I get
```md
## [Unreleased]
### Fixed
- MQTT
### Dependencies
- Bump `maven-source-plugin` from 3.2.1 to 3.3.0 (#23)
  - calculate correct tyre pressure
```

**Comment by tisoft** [comment]
Additionally, if I manually fix the changelog and the action runs again, the fixed Dependencies section is not found and a new broken one is added:
```md
## [Unreleased]
### Fixed
- MQTT
### Dependencies
- Bump `maven-source-plugin` from 3.2.1 to 3.3.0 (#23)
  - calculate correct tyre pressure
### Dependencies
- Bump `maven-source-plugin` from 3.2.1 to 3.3.0 (#23)
```

**Comment by dangoslen** [comment]
Hi Markus.

Thanks for bringing this up. I will have limited time to get to this issue
as I just welcomed a new kiddo into my family (🎉).

I'm happy to review a PR though from you in the meantime if you would like
to take a crack at it! I imagine we are being greedy when looking for a
line in a section.
