### ISSUE TITLE
Dealing with dependabot prefixes

### ISSUE THREAD

**Issue by tartieret** [dangoslen/dependabot-changelog-helper#181]
@dangoslen I really like this github action, I have been looking at this for a while to save time when reviewing dependency updates! Thank you for it. 

However in my projects I use semantic versioning and typical commit prefixes are `chore: ...`, `fix: ...`. As a result by default dependabot adds an additional prefix to its commit messages, such as:
`chore(deps): Bump requests from 2.28.1 to 2.31.0 in /requirements`

Unfortunately it does not seem possible to completely disable the dependabot prefix to remove the `chore(deps): ` part. We can modify it but not set it empty. 

Considering that your action is only able to identify the prefix based on a single word, what would you recommend?

**Comment by dangoslen** [comment]
Hi @tartieret. 

Thanks for your interest here! From what I understand, it sounds like we should expand the capability of the Helper to accommodate your use case. I'd imagine the best path would be to update the [regex](https://github.com/dangoslen/dependabot-changelog-helper/blob/main/src/entry-extractor.ts#L11) that extracts the package data. 

If you are up for a PR I'd be happy to review!

**Comment by dangoslen** [comment]
@tartieret I gave this a quick look actually and I think (if I understand your problem correctly) that a small tweak to the regex should accommodate what you are looking for. Give the linked PR a look!

**Comment by dangoslen** [comment]
This was completed in #182 and was release in v3.4.0
