### ISSUE TITLE
Add support for making the target dependency version and PR a link

### ISSUE THREAD

**Issue by stevehipwell** [dangoslen/dependabot-changelog-helper#188]
When reading a CHANGELOG it's useful to be able to click through to get the context of the changes so being able to click a link to see the version being updated to and the actual PR would make sense.

**Comment by dangoslen** [comment]
Hey @stevehipwell 

This seems related to #149 where we added the link to the original dependabot PR which has all of the context I think you are looking for. 

However, and as discussed in the PR, the implementation relies on GitHub auto-linking to the PR when navigating certain pages (issues, prs, releases). Are you wanting the link added in the CHANGELOG to be a full formated Markdown link then?

**Comment by stevehipwell** [comment]
@dangoslen GH auto linking isn't particularly useful due to a lack of support across GH (this is something GitLab gets right). So yes I'm suggesting any links be explicit instead of relying on auto links.

**Comment by dangoslen** [comment]
Gotcha. Thanks making sure I understand.

I'll look into this, but I do have a busy few weeks and it might be a while for me to write it up. 

I'm always open to review a PR if you would like to take a stab at it though!

**Comment by dangoslen** [comment]
I opened a draft for this - #189.

I do wonder if this should be a configurable behavior to add the full link or just the PR #, especially since it's a change in behavior.

Not sure if you had any thoughts on that or if you wanted to review the PR

**Comment by stevehipwell** [comment]
@dangoslen I can't see a benefit to making this configurable given that where the auto link works this would look the same and where it doesn't work having just a PR # isn't a lot of use. The PR looks good based on the test cases.

**Comment by dangoslen** [comment]
Just release [v3.5.0](https://github.com/dangoslen/dependabot-changelog-helper/releases/tag/v3.5.0), which includes this change!
