### ISSUE TITLE
Bug: Do not add or remove file ending newline character

### ISSUE THREAD

**Issue by SpicyLemon** [dangoslen/dependabot-changelog-helper#199]
As a `dangoslen/dependabot-changelog-helper` user, I would like the lack or presence of a file-ending newline character to be maintained so that the PR diffs are smaller and it's not always getting changed back and forth as other users update the changelog.

Background: In our org, we tell everyone to set up their IDEs to include a newline char at the end of files. This changelog helper keeps trying to delete it the newline at the end of the changelog, though. So the last line of the changelog shows up in the diff a lot, and it'd be nice if that could be kept clean.

**Comment by dangoslen** [comment]
Thanks for raising the issue. I will take a look as soon as I can, which is realistically this weekend. 

Always happy to review a PR if you want to make an update yourself!

**Comment by dangoslen** [comment]
@SpicyLemon - this should be fixed in the upcoming 3.6.0 release. The original PR did _not_ fix it, but I have corrected it while cutting the 3.6.0 release in PR #203
