### ISSUE TITLE
Feature request: Alphabetical sorting

### ISSUE THREAD

**Issue by SubJunk** [dangoslen/dependabot-changelog-helper#252]
It would be cool to add sorting to the dependencies section to make it easier to read

**Comment by dangoslen** [comment]
This is a good idea! And likely straightforward to implement. I'll see what I can do

**Comment by dangoslen** [comment]
I have a prototype of this in #253

**Comment by dangoslen** [comment]
Wow - I just realized I never released this. Should be on it's way soon!

**Comment by SubJunk** [comment]
Awesome!

**Comment by dangoslen** [comment]
Released - [3.9.0](https://github.com/dangoslen/dependabot-changelog-helper/releases/tag/v3.9.0)
